### ISSUE TITLE
Swift compiler errors

### ISSUE THREAD

**Issue by minhongrails** [tokyovigilante/CesiumKit#2]
Hi Ryan,

Thanks a bunch for creating this port!

I wanted to try out your project so I checked out the master branch from Github and attempted to run it. However, I'm getting a bunch of Swift compiler errors like

CesiumKit/CesiumKit/Core/Geometry.swift:160:74: Expected '{' after 'if' condition
CesiumKit/Core/Geometry.swift:160:139: Braced block of statements is an unused closure
CesiumKit/Scene/BingMapsImageryProvider.swift:448:44: Expected type after 'as'
CesiumKit/Scene/BingMapsImageryProvider.swift:448:44: Expected ',' separator
CesiumKit/Scene/BingMapsImageryProvider.swift:448:44: Expected expression in list of expressions

Overall there's around 254 errors. I'm running XCode 6.1.1 and think I'm probably getting these errors because you compiled it with a newer version of Swift? 

I'm gonna try upgrading my XCode but was wondering if you may know what the issue may be

**Comment by tokyovigilante** [comment]
Hi Minh,   

Great, thanks for trying out the code! You’ll definitely need to upgrade to Xcode 6.3 unfortunately as I’m using Swift 1.2. Master should work fine after that though, let me know if you’re having any other errors.

I’ll add that to the Readme.  

Regards,

Ryan

**Comment by minhongrails** [comment]
That worked, thanks!

**Comment by tokyovigilante** [comment]
Great, how did you get on testing?

**Comment by minhongrails** [comment]
So far I was able to load it on to my iPad2 Air and it looked like it was working without any errors but all I was able to do from the UI was view the initial viewport of the globe. I'm still learning the codebase but I'm going to try playing around with the external API.

**Comment by tokyovigilante** [comment]
That's great. At the moment there is no real UI as I haven't implemented touch camera controls. If you are interested in working this, I am planning to mentor a GSOC student to work on the UI.

**Comment by minhongrails** [comment]
Sure, I'll be glad to help however I can :). I'm not technically a student, though. I've actually been in the industry for around 7+ years lol, although my background is primarily in Java and web development (JavaScript, Angular, Sass). Recently, for my day job I've been working with CesiumJS quite a bit, though

However, in my free time I've been teaching myself iOS (core objective c) and Swift.

**Comment by tokyovigilante** [comment]
Good man, well you're very welcome to contribute. This is a personal and part-time project for me too, just hoping to make something worthwhile that people can use and extend.

Let me know if you have any questions or suggestions (ryan@testtoast.com).

Regards,

Ryan
