### ISSUE TITLE
No such module GLSLOptimizer

### ISSUE THREAD

**Issue by qhccthanh** [tokyovigilante/CesiumKit#9]
Hi tokyovigilante, 

I try to run ios demo and CesiumKit. But PMJSON and GLSLOptimizer not available in git. I have added PMJSON to this project. However, [GLSLOptimizer](https://github.com/aras-p/glsl-optimizer)
 i add glsl_optimizer_lib.xcodeproj to this project but still error No such module GLSLOptimizer.

**Comment by tokyovigilante** [comment]
Hi, 

There is script called getDependencies.sh in the root of the project which will fetch both PMJSON and glsl_optimizer. I am planning to update these dependencies and use the Swift package manager once it is a little more mature.

Let me know how you get on.

**Comment by qhccthanh** [comment]
Hi tokyovigilante, 

How can i run this script ? I use Cesiumjs in iOS through UIWebView, but it render and performance very bad. I found CesiumKit and try to run it. I use Cesium to build custom map like Pokemongo + 3d building. 

Best regards.

**Comment by tokyovigilante** [comment]
Just run it in a terminal from the root of the source directory as per the README.

Please also note that only the basics of the globe with terrain and atmosphere are present. There is no custom model or CZML support which will limit your ability to build apps on top of the toolkit as it is currently.

**Comment by qhccthanh** [comment]
I have run it. It use a lot of memory about (500mb >) in iPhone 6 iOS 10.2.1. Thanks your advise and support.

**Comment by tokyovigilante** [comment]
Glad you were able to get it up and running. There are some cache optimisations which will hopefully be made in due course, but globe rendering does require a significant amount of memory particularly if both terrain and imagery are loaded.
